name = "ModelCriticism"
uuid = "591160b1-14da-46d3-9030-6b05f6e62482"
authors = ["Joshua C. Macdonald <jmacdo16@jh.edu>"]
version = "0.1.0"

[deps]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
